# Generated by Django 6.0.2 on 2026-03-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_data_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['company__name', '-is_company_admin', 'username', 'id']},
        ),
    ]
