# Generated by Django 6.0.2 on 2026-03-20 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_master_partner'),
        ('reccon_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('master_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_reconciliations', to='companies.company')),
                ('slave_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_reconciliations', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_chat_messages', to='companies.company')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='reconciliations.reconciliation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='reconciliations.reconciliation')),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationStageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_snapshot', models.CharField(max_length=255)),
                ('status_snapshot', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('confirmed', 'Confirmed')], max_length=16)),
                ('sent_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_slave', models.BooleanField(default=False)),
                ('confirmed_by_slave_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_stage_items', to='reccon_messages.message')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliations.reconciliationstage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationstage',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'stage_number'), name='unique_stage_number_per_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationstageitem',
            constraint=models.UniqueConstraint(fields=('stage', 'message'), name='unique_message_per_stage'),
        ),
    ]
