# Generated by Django 6.0.2 on 2026-03-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboxevent',
            options={'ordering': ['-created_at']},
        ),
    ]
