# Generated by Django 6.0.2 on 2026-02-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='master_partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'company_type': 'master'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slave_partners', to='companies.company'),
        ),
    ]
