# Generated by Django 6.0.2 on 2026-03-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name', 'id']},
        ),
    ]
