# Generated by Django 6.0.2 on 2026-02-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('read', 'Read'), ('confirmed', 'Confirmed')], max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to='companies.company')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='companies.company')),
            ],
        ),
    ]
