# Generated by Django 6.0.2 on 2026-03-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_master_partner'),
        ('reccon_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type', models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=16)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('sender_company', 'sender_number'), name='unique_sender_number_per_sender_company'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('receiver_company', 'receiver_number'), name='unique_receiver_number_per_receiver_company'),
        ),
        migrations.AddField(
            model_name='messagenumbercounter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_number_counters', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='messagenumbercounter',
            constraint=models.UniqueConstraint(fields=('company', 'counter_type'), name='unique_counter_type_per_company'),
        ),
    ]
