# Generated by Django 6.0.2 on 2026-03-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccon_messages', '0003_message_body_html_and_subject_blank'),
        ('reconciliations', '0002_reconciliationchatmessage_stage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='late_send_reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_sent_messages', to='reconciliations.reconciliation'),
        ),
    ]
